version: '3.9'

services:
  portfolio:
    build: .
    container_name: portfolio
    restart: always
    ports:
      - "8002:8000"  # 8001 na VPS, 8000 no container
    env_file:
      - .env          # Variáveis de ambiente com DB
    volumes:
      - .:/app        # Sincroniza código local com container
