# Generated by Django 5.2.7 on 2025-10-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrasesCima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=255)),
                ('frase_pt', models.CharField(max_length=255)),
                ('frase_en', models.CharField(max_length=255)),
                ('frase_es', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Frase cima',
                'verbose_name_plural': 'Frases cima',
            },
        ),
        migrations.CreateModel(
            name='FrasesInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=255)),
                ('frase_pt', models.CharField(max_length=255)),
                ('frase_en', models.CharField(max_length=255)),
                ('frase_es', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Frase de inicio',
                'verbose_name_plural': 'Frases de inicio',
            },
        ),
        migrations.CreateModel(
            name='SubFrasesInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase_pt', models.CharField(max_length=255)),
                ('frase_en', models.CharField(max_length=255)),
                ('frase_es', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Subfrase de inicio',
                'verbose_name_plural': 'Subfrases de inicio',
            },
        ),
    ]
