# Generated by Django 5.2.7 on 2025-10-29 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0003_rename_configuracoes_configuracoe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubFrasesInicio',
        ),
    ]
