# Generated by Django 5.2.7 on 2025-10-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0004_delete_subfrasesinicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frasesinicio',
            options={'verbose_name': 'Frases Principal', 'verbose_name_plural': 'Frases Principais'},
        ),
    ]
