# Generated by Django 5.2.7 on 2025-10-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0005_alter_frasesinicio_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frasesinicio',
            options={'verbose_name': 'Frase de inicio', 'verbose_name_plural': 'Frases de inicio'},
        ),
        migrations.RenameField(
            model_name='frasesinicio',
            old_name='frase_en',
            new_name='frase_frase_principal_en',
        ),
        migrations.RenameField(
            model_name='frasesinicio',
            old_name='frase_es',
            new_name='frase_principal_pt',
        ),
        migrations.RenameField(
            model_name='frasesinicio',
            old_name='frase_pt',
            new_name='subfrase_principal_en',
        ),
        migrations.AddField(
            model_name='frasesinicio',
            name='subfrase_principal_pt',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
