# Generated by Django 5.2.7 on 2025-10-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0006_alter_frasesinicio_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frasesinicio',
            name='frase_frase_principal_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='frasesinicio',
            name='frase_principal_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='frasesinicio',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='frasesinicio',
            name='subfrase_principal_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='frasesinicio',
            name='subfrase_principal_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
