# Generated by Django 5.2.7 on 2025-10-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0007_alter_frasesinicio_frase_frase_principal_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frasescima',
            name='frase_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='frasescima',
            name='frase_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='frasescima',
            name='frase_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='frasescima',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
