# Generated by Django 5.2.7 on 2025-10-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0008_alter_frasescima_frase_en_alter_frasescima_frase_es_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contato do Terminal',
                'verbose_name_plural': 'Contatos do Terminal',
            },
        ),
    ]
