# Generated by Django 5.2.7 on 2025-10-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0009_contatoterminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatoterminal',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
