# Generated by Django 5.2.7 on 2025-10-30 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('preview_url', models.URLField()),
                ('foto_principal', models.ImageField(upload_to='fotos_projetos')),
            ],
        ),
        migrations.CreateModel(
            name='FotoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos_projetos/galeria/')),
                ('legenda', models.CharField(blank=True, max_length=255, null=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='servicos.projeto')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
