# Generated by Django 5.2.7 on 2025-10-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_biblioteca_tipoprojeto_projeto_ano_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='biblioteca',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='tipo_projeto',
        ),
        migrations.AddField(
            model_name='projeto',
            name='bibliotecas',
            field=models.ManyToManyField(blank=True, related_name='projetos', to='servicos.biblioteca'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='tipos',
            field=models.ManyToManyField(blank=True, related_name='projetos', to='servicos.tipoprojeto'),
        ),
    ]
